### ISSUE TITLE
combile error: fatal error: strcase.h: No such file or directory

### ISSUE THREAD

**Issue by liusdu** [virtualsquare/vuos#20]
Hi  @rd235 
I  try compile  vuos project, but failed with error "vufuse/vufuse_startmain.c:25:10: fatal error: strcase.h: No such file or directory".

And after glace the code.  I think it provides "strcase" and "STRCASE". And I can not find `strcase.h` containes these two functions or macros.   So how can I get `strcase.h`?

**Comment by liusdu** [comment]
Sorry, I fixed it.

**Comment by rd235** [comment]
The dependency from https://github.com/rd235/strcase.git is listed in README.md
